// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvAC5JMlDxhAsbRTGWbWGXNBl1VV2vjww',
    appId: '1:1017363866428:web:2b63ce6c71e34629b4b439',
    messagingSenderId: '1017363866428',
    projectId: 'blogfinal-53195',
    authDomain: 'blogfinal-53195.firebaseapp.com',
    storageBucket: 'blogfinal-53195.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJV7zWksXIxFw7T8UP80LDEIf95hhDp8',
    appId: '1:1017363866428:android:15c405d3e980a769b4b439',
    messagingSenderId: '1017363866428',
    projectId: 'blogfinal-53195',
    storageBucket: 'blogfinal-53195.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgD3mqQTaOXN_WB3jyOft1N4C3YAtM9b0',
    appId: '1:1017363866428:ios:c1b5d8467ef0d985b4b439',
    messagingSenderId: '1017363866428',
    projectId: 'blogfinal-53195',
    storageBucket: 'blogfinal-53195.appspot.com',
    iosBundleId: 'com.example.blogFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgD3mqQTaOXN_WB3jyOft1N4C3YAtM9b0',
    appId: '1:1017363866428:ios:cb102e0972788688b4b439',
    messagingSenderId: '1017363866428',
    projectId: 'blogfinal-53195',
    storageBucket: 'blogfinal-53195.appspot.com',
    iosBundleId: 'com.example.blogFinal.RunnerTests',
  );
}
